/* eslint-disable @next/next/no-sync-scripts */
import React from "react"
import Todo from "./componenets/todo"
import Icones from "./componenets/icones"
import Link from "next/link"
import Head from "next/head"
import List from "./componenets/Liste"
import styles from "../styles/Home.module.css"


export default function Home() {
  return (
    <div className={styles.container} >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" integrity="sha512-iBBXm8fW90+nuLcSKlbmrPcLa0OT92xO1BIsZ+ywDWZCvqsWgccV3gFoRBv0z+8dLJgyAHIhR35VZc2oM/gI1w==" crossOrigin="anonymous" referrerPolicy="no-referrer" />
        <script src="https://cdn.tailwindcss.com"></script>
      </Head>
      <div className="m-0 bg-zinc-50 font-sans">
        <div className="text-center mt-4 mb-4 header">
          <h1 className="text-3xl font-extrabold underline decoration-blue-500 ">My todoList</h1>
        </div>
        <Todo />
        <hr className="line  h-px bg-gray-200 border-0 dark:bg-gray-700"></hr>
        <Icones />
        <List name="test" />
        <List name="apprendre l'algorithme" />
        <List name="bdd" />
      </div>
    </div>
  )
}
